# Generated by Django 3.2.12 on 2022-04-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-popularity'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
